'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'te' | 'kn' | 'mr' | 'hinglish';

interface LanguageContextType {
  currentLanguage: SupportedLanguage;
  setLanguage: (language: SupportedLanguage) => void;
  t: (key: string, section?: string) => string | string[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Global translations object
const translations = {
  // Common UI elements
  common: {
    en: {
      back: 'Back',
      next: 'Next',
      submit: 'Submit',
      finish: 'Finish',
      cancel: 'Cancel',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      confirm: 'Confirm',
      loading: 'Loading...',
      processing: 'Processing...',
      note: 'Note',
      getHelp: '🎯 Get Help',
      requestCallback: '📞 Request Callback',
      backToServices: 'Back to Services',
      welcomeBack: 'Welcome back',
      chooseLanguage: 'Choose Language',
      applicationId: 'Application ID',
      status: 'Status',
      amount: 'Amount',
      createdOn: 'Created On',
      requestedOn: 'Requested On',
      available: 'Available',
      max: 'Max',
      yes: 'Yes',
      no: 'No',
      close: 'Close',
      continue: 'Continue',
      startTour: 'Start Tour',
      skipTour: 'Skip Tour',
      reason: 'Reason',
      changeStatus: 'Change Status',
      callbackRegistered: 'Callback Request Registered',
      callbackMessage: 'Our team will contact you soon!',
      viewDetails: 'View Details',
      newApplication: 'New Application',
      continueApplication: 'Continue Application',
      learnMore: 'Learn More',
      startApplication: 'Start Application'
    },
    hi: {
      back: 'पीछे',
      next: 'आगे',
      submit: 'जमा करें',
      finish: 'समाप्त',
      cancel: 'रद्द करें',
      save: 'सहेजें',
      edit: 'संपादित करें',
      delete: 'हटाएं',
      confirm: 'पुष्टि करें',
      loading: 'लोड हो रहा है...',
      processing: 'प्रसंस्करण...',
      note: 'नोट',
      getHelp: '🎯 सहायता प्राप्त करें',
      requestCallback: '📞 कॉलबैक अनुरोध',
      backToServices: 'सेवाओं पर वापस जाएं',
      welcomeBack: 'वापसी पर स्वागत है',
      chooseLanguage: 'भाषा चुनें',
      applicationId: 'आवेदन आईडी',
      status: 'स्थिति',
      amount: 'राशि',
      createdOn: 'बनाया गया',
      requestedOn: 'अनुरोध किया गया',
      available: 'उपलब्ध',
      max: 'अधिकतम',
      yes: 'हाँ',
      no: 'नहीं',
      close: 'बंद करें',
      continue: 'जारी रखें',
      startTour: 'टूर शुरू करें',
      skipTour: 'टूर छोड़ें',
      reason: 'कारण',
      changeStatus: 'स्थिति बदलें',
      callbackRegistered: 'कॉलबैक अनुरोध दर्ज',
      callbackMessage: 'हमारी टीम जल्द ही आपसे संपर्क करेगी!',
      viewDetails: 'विवरण देखें',
      newApplication: 'नया आवेदन',
      continueApplication: 'आवेदन जारी रखें',
      learnMore: 'और जानें',
      startApplication: 'आवेदन शुरू करें'
    }
  },
  
  // KYC Page
  kyc: {
    en: {
      title: 'KYC Verification',
      subtitle: 'Complete your verification to access our services',
      personalDetails: 'Personal Details',
      fullName: 'Full Name',
      fullNamePlaceholder: 'Enter your full name',
      mobileNumber: 'Mobile Number',
      mobilePlaceholder: 'Enter your mobile number',
      gender: 'Gender',
      selectGender: 'Select gender',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      documentUpload: 'Document Upload',
      panCard: 'PAN Card',
      panCardPlaceholder: 'Click to upload PAN Card',
      aadhaarCard: 'Aadhaar Card',
      aadhaarPlaceholder: 'Click to upload Aadhaar Card',
      liveSelfie: 'Live Selfie',
      captureSelfie: 'Capture Selfie',
      retakeSelfie: 'Retake Selfie',
      selfieCaptured: 'Selfie captured successfully!',
      otpVerification: 'OTP Verification',
      otpSentMessage: 'We\'ve sent a 6-digit OTP to',
      otpPlaceholder: 'Enter OTP',
      didntReceiveOtp: 'Didn\'t receive OTP? Resend',
      verificationComplete: 'Verification Complete!',
      verificationSuccess: 'Your KYC has been verified successfully!',
      proceedToServices: 'Proceed to Services',
      step: 'Step',
      of: 'of',
      sendingOtp: 'Sending OTP...',
      verifyingOtp: 'Verifying OTP...',
      verifyComplete: 'Verify & Complete',
      switchCamera: 'Switch Camera',
      selfieCapture: 'Selfie Capture',
      uploadFile: 'Upload File',
      fileSelected: 'File Selected',
      // Tour and Help Messages
      welcomeBack: 'Welcome back!',
      continuingFromStep: 'You\'re continuing from step {step} of {total}.',
      getHelpForStep: 'Get Help for Step {step}',
      complete: 'Complete',
      selfieHelp: 'Take a clear selfie in good lighting. Make sure your face is clearly visible and you\'re looking directly at the camera.',
      documentHelp: 'Upload clear, high-quality images of your documents. Make sure all text is readable and the documents are not expired.',
      otpHelp: 'We\'ll send a 6-digit OTP to your registered mobile number. Enter the code exactly as received. If you don\'t receive it, you can request a new one.',
      // KYC Tour Texts
      personalDetailsTourText: 'Welcome to KYC verification! Let\'s start with your personal details. Fill in your name, mobile number, and select your gender.',
      documentUploadTourText: 'Great! Now let\'s upload your documents. You\'ll need your PAN Card and Aadhaar Card. Make sure they are clear and readable.',
      selfieCaptureTourText: 'Almost there! Now take a live selfie using your device camera. This helps us verify your identity.',
      otpVerificationTourText: 'Final step! We\'ll send an OTP to your mobile number for verification. Enter the 6-digit code when you receive it.',
      gotIt: 'Got it!',
      personalDetailsHelp: 'Please provide your complete details as they appear on your official documents. This information will be used for verification purposes.'
    },
    hi: {
      title: 'केवाईसी सत्यापन',
      subtitle: 'हमारी सेवाओं का उपयोग करने के लिए अपना सत्यापन पूरा करें',
      personalDetails: 'व्यक्तिगत विवरण',
      fullName: 'पूरा नाम',
      fullNamePlaceholder: 'अपना पूरा नाम दर्ज करें',
      mobileNumber: 'मोबाइल नंबर',
      mobilePlaceholder: 'अपना मोबाइल नंबर दर्ज करें',
      gender: 'लिंग',
      selectGender: 'लिंग चुनें',
      male: 'पुरुष',
      female: 'महिला',
      other: 'अन्य',
      documentUpload: 'दस्तावेज़ अपलोड',
      panCard: 'पैन कार्ड',
      panCardPlaceholder: 'पैन कार्ड अपलोड करने के लिए क्लिक करें',
      aadhaarCard: 'आधार कार्ड',
      aadhaarPlaceholder: 'आधार कार्ड अपलोड करने के लिए क्लिक करें',
      liveSelfie: 'लाइव सेल्फी',
      captureSelfie: 'सेल्फी लें',
      retakeSelfie: 'दोबारा सेल्फी लें',
      selfieCaptured: 'सेल्फी सफलतापूर्वक ली गई!',
      otpVerification: 'ओटीपी सत्यापन',
      otpSentMessage: 'हमने 6 अंकों का ओटीपी भेजा है',
      otpPlaceholder: 'ओटीपी दर्ज करें',
      didntReceiveOtp: 'ओटीपी नहीं मिला? दोबारा भेजें',
      verificationComplete: 'सत्यापन पूर्ण!',
      verificationSuccess: 'आपका केवाईसी सफलतापूर्वक सत्यापित हो गया है!',
      proceedToServices: 'सेवाओं पर जाएं',
      step: 'चरण',
      of: 'का',
      sendingOtp: 'ओटीपी भेजा जा रहा है...',
      verifyingOtp: 'ओटीपी सत्यापित हो रहा है...',
      verifyComplete: 'सत्यापित करें और पूर्ण करें',
      switchCamera: 'कैमरा बदलें',
      selfieCapture: 'सेल्फी कैप्चर',
      uploadFile: 'फ़ाइल अपलोड करें',
      fileSelected: 'फ़ाइल चुनी गई',
      // Tour and Help Messages
      welcomeBack: 'वापस स्वागत है!',
      continuingFromStep: 'आप चरण {step} से {total} में से जारी रख रहे हैं।',
      getHelpForStep: 'चरण {step} के लिए सहायता प्राप्त करें',
      complete: 'पूर्ण',
      selfieHelp: 'अच्छी रोशनी में स्पष्ट सेल्फी लें। सुनिश्चित करें कि आपका चेहरा स्पष्ट रूप से दिखाई दे रहा है और आप कैमरे की तरफ सीधे देख रहे हैं।',
      documentHelp: 'अपने दस्तावेजों की स्पष्ट, उच्च गुणवत्ता वाली छवियां अपलोड करें। सुनिश्चित करें कि सभी टेक्स्ट पढ़ने योग्य है और दस्तावेज समाप्त नहीं हुए हैं।',
      otpHelp: 'हम आपके पंजीकृत मोबाइल नंबर पर 6 अंकों का OTP भेजेंगे। प्राप्त कोड को बिल्कुल वैसे ही दर्ज करें जैसे मिला है। यदि आपको नहीं मिलता, तो आप नया अनुरोध कर सकते हैं।',
      // KYC Tour Texts
      personalDetailsTourText: 'KYC सत्यापन में आपका स्वागत है! आइए अपने व्यक्तिगत विवरण से शुरू करते हैं। अपना नाम, मोबाइल नंबर भरें और अपना लिंग चुनें।',
      documentUploadTourText: 'बहुत बढ़िया! अब आइए अपने दस्तावेज अपलोड करते हैं। आपको अपना PAN कार्ड और आधार कार्ड चाहिए। सुनिश्चित करें कि वे स्पष्ट और पठनीय हैं।',
      selfieCaptureTourText: 'लगभग हो गया! अब अपने डिवाइस कैमरे का उपयोग करके एक लाइव सेल्फी लें। यह हमें आपकी पहचान सत्यापित करने में मदद करता है।',
      otpVerificationTourText: 'अंतिम चरण! हम सत्यापन के लिए आपके मोबाइल नंबर पर एक OTP भेजेंगे। जब आपको मिले तो 6 अंकों का कोड दर्ज करें।',
      gotIt: 'समझ गया!',
      personalDetailsHelp: 'कृपया अपने आधिकारिक दस्तावेजों में दिखाई देने वाले अपने पूरे विवरण प्रदान करें। यह जानकारी सत्यापन प्रयोजनों के लिए उपयोग की जाएगी।'
    }
  },
  
  // Services page
  services: {
    en: {
      title: 'Choose Your Service',
      subtitle: 'Welcome back! What would you like to do today?',
      loanService: 'Loan Application',
      loanDescription: 'Apply for a personal loan with competitive interest rates',
      loanFeatures: [
        'Quick approval process',
        'Flexible repayment options',
        'Competitive interest rates',
        'No hidden charges'
      ],
      ewaService: 'EWA (Earned Wage Access)',
      ewaDescription: 'Access your earned wages before payday',
      ewaFeatures: [
        'Instant access to earned wages',
        'No interest or fees',
        'Flexible withdrawal amounts',
        'Secure and safe'
      ],
      startApplication: 'Start Application',
      continueApplication: 'Continue Application',
      accessDashboard: 'Access Dashboard',
      newApplication: 'New Application',
      kycVerified: 'KYC Verified',
      active: 'Active',
      inProgress: 'In Progress',
      tip: 'Tip',
      tipMessage: 'You can start with either service. Your KYC information will be automatically filled in.',
      // Services Tour Texts
      welcomeToServicesDashboard: 'Welcome to Your Services Dashboard! 🎉',
      kycVerifiedExplore: 'Now that your KYC is verified, you can choose between two financial services.',
      letsExploreServices: 'Let\'s explore what\'s available for you!',
      loanApplicationService: 'Loan Application Service 💰',
      loanServiceOffers: 'This service offers:',
      personalLoansCompetitive: 'Personal loans with competitive rates',
      quickApprovalProcess: 'Quick approval process',
      flexibleRepaymentOptions: 'Flexible repayment options',
      noHiddenCharges: 'No hidden charges',
      perfectForMoney: 'Perfect if you need money for any purpose!',
      ewaEarnedWageAccess: 'EWA (Earned Wage Access) 💳',
      ewaServiceAllows: 'This service allows you to:',
      accessEarnedWagesEarly: 'Access your earned wages before payday',
      withdrawMoneyInstantly: 'Withdraw money instantly when needed',
      noInterestFeesCharged: 'No interest or fees charged',
      flexibleWithdrawalAmounts: 'Flexible withdrawal amounts',
      greatForEmergencies: 'Great for emergency expenses!',
      kycVerificationBenefits: 'KYC Verification Benefits ✅',
      sinceKycVerified: 'Since your KYC is verified:',
      detailsPreFilled: 'All your details are pre-filled',
      fasterApplicationProcess: 'Faster application process',
      noDocumentsAgain: 'No need to upload documents again',
      quickApprovalDisbursement: 'Quick approval and disbursement',
      allSetToApply: 'You\'re all set to apply for any service!',
      finishTour: 'Finish Tour',
      previous: 'Previous'
    },
    hi: {
      title: 'अपनी सेवा चुनें',
      subtitle: 'वापसी पर स्वागत है! आज आप क्या करना चाहते हैं?',
      loanService: 'ऋण आवेदन',
      loanDescription: 'प्रतिस्पर्धी ब्याज दरों के साथ व्यक्तिगत ऋण के लिए आवेदन करें',
      loanFeatures: [
        'त्वरित स्वीकृति प्रक्रिया',
        'लचीली चुकौती विकल्प',
        'प्रतिस्पर्धी ब्याज दरें',
        'कोई छिपे हुए शुल्क नहीं'
      ],
      ewaService: 'EWA (अर्जित वेतन पहुंच)',
      ewaDescription: 'पेडे से पहले अपने अर्जित वेतन तक पहुंचें',
      ewaFeatures: [
        'अर्जित वेतन तक तत्काल पहुंच',
        'कोई ब्याज या शुल्क नहीं',
        'लचीली निकासी राशि',
        'सुरक्षित और सुरक्षित'
      ],
      startApplication: 'आवेदन शुरू करें',
      continueApplication: 'आवेदन जारी रखें',
      accessDashboard: 'डैशबोर्ड एक्सेस करें',
      newApplication: 'नया आवेदन',
      kycVerified: 'KYC सत्यापित',
      active: 'सक्रिय',
      inProgress: 'प्रगति में',
      tip: 'सुझाव',
      tipMessage: 'आप किसी भी सेवा के साथ शुरुआत कर सकते हैं। आपकी KYC जानकारी स्वचालित रूप से भर जाएगी।',
      // Services Tour Texts
      welcomeToServicesDashboard: 'आपके सेवा डैशबोर्ड में स्वागत है! 🎉',
      kycVerifiedExplore: 'अब जब आपका KYC सत्यापित हो गया है, आप दो वित्तीय सेवाओं में से चुन सकते हैं।',
      letsExploreServices: 'आइए देखते हैं कि आपके लिए क्या उपलब्ध है!',
      loanApplicationService: 'लोन आवेदन सेवा 💰',
      loanServiceOffers: 'यह सेवा प्रदान करती है:',
      personalLoansCompetitive: 'प्रतिस्पर्धी दरों के साथ व्यक्तिगत लोन',
      quickApprovalProcess: 'त्वरित अनुमोदन प्रक्रिया',
      flexibleRepaymentOptions: 'लचीले चुकौती विकल्प',
      noHiddenCharges: 'कोई छिपे हुए शुल्क नहीं',
      perfectForMoney: 'किसी भी उद्देश्य के लिए पैसे की जरूरत हो तो बिल्कुल सही!',
      ewaEarnedWageAccess: 'EWA (अर्जित वेतन पहुंच) 💳',
      ewaServiceAllows: 'यह सेवा आपको अनुमति देती है:',
      accessEarnedWagesEarly: 'वेतन दिवस से पहले अपने अर्जित वेतन तक पहुंच',
      withdrawMoneyInstantly: 'जरूरत पड़ने पर तुरंत पैसे निकालना',
      noInterestFeesCharged: 'कोई ब्याज या शुल्क नहीं लिया जाता',
      flexibleWithdrawalAmounts: 'लचीली निकासी राशि',
      greatForEmergencies: 'आपातकालीन खर्चों के लिए बहुत बढ़िया!',
      kycVerificationBenefits: 'KYC सत्यापन लाभ ✅',
      sinceKycVerified: 'चूंकि आपका KYC सत्यापित है:',
      detailsPreFilled: 'आपके सभी विवरण पहले से भरे हुए हैं',
      fasterApplicationProcess: 'तेज़ आवेदन प्रक्रिया',
      noDocumentsAgain: 'दस्तावेज़ दोबारा अपलोड करने की जरूरत नहीं',
      quickApprovalDisbursement: 'त्वरित अनुमोदन और वितरण',
      allSetToApply: 'आप किसी भी सेवा के लिए आवेदन करने के लिए तैयार हैं!',
      finishTour: 'टूर समाप्त करें',
      previous: 'पिछला'
    }
  },

  // EWA pages
  ewa: {
    en: {
      title: 'EWA Dashboard',
      subtitle: 'Manage your Earned Wage Access account',
      newWithdrawalRequest: 'New Withdrawal Request',
      withdrawalAmount: 'Withdrawal Amount',
      withdrawalRequests: 'Withdrawal Requests',
      submitRequest: 'Submit Request',
      noRequestsYet: 'No withdrawal requests yet',
      makeFirstRequest: 'Make your first withdrawal request to get started',
      maxMonthlyLimit: 'Max Monthly Limit',
      currentBalance: 'Current Balance',
      pendingWithdrawals: 'Pending Withdrawals',
      cannotMakeNewRequest: 'You cannot make a new request until all existing requests are either rejected or disbursed.',
      reason: 'Reason',
      requestId: 'Request ID',
      // Status translations
      requested: '📋 Requested',
      processing: '⏳ Processing',
      completed: '✅ Completed',
      disbursed: '💰 Disbursed',
      rejected: '❌ Rejected',
      withdrawalLimit: 'Your withdrawal limit',
      usedThisMonth: 'Used This Month',
      amountWithdrawn: 'Amount withdrawn',
      readyToWithdraw: 'Ready to withdraw',
      // EWA Disbursement Details
      ewaWithdrawalDetails: 'EWA Withdrawal Details',
      trackWithdrawalStatus: 'Track your withdrawal status and repayment information',
      backToDashboard: 'Back to Dashboard',
      withdrawalSummary: 'Withdrawal Summary',
      requestedAmount: 'Requested Amount',
      processingFee: 'Processing Fee',
      netAmountReceived: 'Net Amount Received',
      ofAmount: 'of amount',
      repaymentInformation: 'Repayment Information',
      repaymentDate: 'Repayment Date',
      nextSalaryDate: 'Next salary date',
      repaymentAmount: 'Repayment Amount',
      fullAmountDeducted: 'Full amount will be deducted',
      withdrawalTermsConditions: 'Withdrawal Terms & Conditions',
      withdrawalRules: 'Withdrawal Rules',
      maxWithdrawalLimit: 'Maximum withdrawal limit (80% of salary)',
      processingFeeInfo: 'Processing fee: 2% of withdrawal amount',
      repaymentAutoDeduction: 'Repayment automatically deducted from next salary',
      importantNotes: 'Important Notes',
      instantTransfer: 'Instant transfer to your registered bank account',
      noInterestCharge: 'No interest charges - only processing fee',
      lateDeductionFee: 'Late deduction fee: ₹200 if salary is insufficient',
      // Tour texts
      yourWithdrawalDetails: 'Your Withdrawal Details',
      hereYouCanSee: 'Here you can see',
      processingFees: 'Processing fees and charges',
      repaymentSchedule: 'Repayment schedule',
      repaymentDetails: 'Repayment Details',
      repaymentDetailsText: 'This section shows when and how the amount will be repaid',
      withdrawalTerms: 'Withdrawal Terms',
      importantTerms: 'Important Terms',
      withdrawalTermsText: 'Please review these important terms and conditions',
      // EWA Application Pages
      ewaApplication: 'EWA Application',
      setupEarnedWageAccess: 'Set up your Earned Wage Access account',
      ewaConsentSetup: 'EWA Consent & Setup',
      completeSetupEarnedWageAccess: 'Complete the setup for your Earned Wage Access account',
      consentAuthorization: 'Consent & Authorization',
      consentText: 'I hereby consent and authorize the company to fetch my employment and salary information from my employer for the purpose of setting up Earned Wage Access. I understand that this information will be used solely for EWA assessment and approval.',
      agreeTermsConditions: 'I agree to the terms and conditions',
      yourEWALimits: 'Your EWA Limits',
      maxDrawdown: 'Max Drawdown',
      basedOnSalary: 'Based on your salary You can withdraw up to the above amount before payday',
      completeSetupProceedMandate: 'Complete Setup & Proceed to Mandate',
      kycInfoAutomaticallyFilled: 'Your KYC information has been automatically filled in. You can start using EWA',
      // EWA Success Page
      ewaAgreementSignedSuccessfully: 'EWA Agreement Signed Successfully!',
      ewaAgreementProcessed: 'Your EWA agreement has been digitally signed and processed. You will be redirected to your dashboard shortly.',
      agreementSignedActivated: 'Agreement signed and activated. You can now access your EWA services.',
      settingUpEWA: 'Setting up EWA...',
      // EWA Digital Signature
      keyTermsEWAAgreement: 'Key Terms of Your EWA Agreement',
      maxWithdrawalMonthly: 'Maximum withdrawal',
      withdrawalFrequency: 'Withdrawal frequency',
      monthly: 'Monthly',
      noInterestFees: 'No interest or fees charged',
      autoSalaryDeduction: 'Automatic salary deduction on payday',
      bankMandateAuth: 'Bank mandate authorization',
      privacyDataTerms: 'Privacy and data usage terms',
      digitalSignature: 'Digital Signature',
      signContractAcknowledge: 'By clicking "Sign Contract" below, I acknowledge that:',
      readUnderstoodAgreement: 'I have read and understood the complete EWA agreement',
      agreeAllTermsDocument: 'I agree to all terms and conditions mentioned in the document',
      authorizeAutoDeduction: 'I authorize the automatic deduction setup as per the agreement',
      digitalSignatureLegallyBinding: 'This digital signature is legally binding',
      signContract: 'Sign Contract'
    },
    hi: {
      title: 'EWA डैशबोर्ड',
      subtitle: 'अपने अर्जित वेतन पहुंच खाते का प्रबंधन करें',
      newWithdrawalRequest: 'नई निकासी अनुरोध',
      withdrawalAmount: 'निकासी राशि',
      withdrawalRequests: 'निकासी अनुरोध',
      submitRequest: 'अनुरोध जमा करें',
      noRequestsYet: 'अभी तक कोई निकासी अनुरोध नहीं',
      makeFirstRequest: 'शुरुआत करने के लिए अपना पहला निकासी अनुरोध करें',
      maxMonthlyLimit: 'अधिकतम मासिक सीमा',
      currentBalance: 'वर्तमान शेष',
      pendingWithdrawals: 'लंबित निकासी',
      cannotMakeNewRequest: 'आप तब तक नया अनुरोध नहीं कर सकते जब तक कि सभी मौजूदा अनुरोध अस्वीकृत या वितरित नहीं हो जाते।',
      reason: 'कारण',
      requestId: 'अनुरोध आईडी',
      // Status translations
      requested: '📋 अनुरोधित',
      processing: '⏳ प्रसंस्करण',
      completed: '✅ पूर्ण',
      disbursed: '💰 वितरित',
      rejected: '❌ अस्वीकृत',
      withdrawalLimit: 'आपकी निकासी सीमा',
      usedThisMonth: 'इस महीने उपयोग किया गया',
      amountWithdrawn: 'निकासी की गई राशि',
      readyToWithdraw: 'निकासी के लिए तैयार',
      // EWA Disbursement Details
      ewaWithdrawalDetails: 'EWA निकासी विवरण',
      trackWithdrawalStatus: 'अपनी निकासी स्थिति और वापसी जानकारी को ट्रैक करें',
      backToDashboard: 'डैशबोर्ड पर वापस जाएं',
      withdrawalSummary: 'निकासी सारांश',
      requestedAmount: 'अनुरोधित राशि',
      processingFee: 'प्रसंस्करण शुल्क',
      netAmountReceived: 'प्राप्त शुद्ध राशि',
      ofAmount: 'राशि का',
      repaymentInformation: 'वापसी जानकारी',
      repaymentDate: 'वापसी तिथि',
      nextSalaryDate: 'अगली वेतन तिथि',
      repaymentAmount: 'वापसी राशि',
      fullAmountDeducted: 'पूरी राशि काट ली जाएगी',
      withdrawalTermsConditions: 'निकासी नियम और शर्तें',
      withdrawalRules: 'निकासी नियम',
      maxWithdrawalLimit: 'अधिकतम निकासी सीमा (वेतन का 80%)',
      processingFeeInfo: 'प्रसंस्करण शुल्क: निकासी राशि का 2%',
      repaymentAutoDeduction: 'अगले वेतन से स्वचालित रूप से वापसी काट ली जाएगी',
      importantNotes: 'महत्वपूर्ण नोट्स',
      instantTransfer: 'आपके पंजीकृत बैंक खाते में तुरंत स्थानांतरण',
      noInterestCharge: 'कोई ब्याज शुल्क नहीं - केवल प्रसंस्करण शुल्क',
      lateDeductionFee: 'देर से कटौती शुल्क: यदि वेतन अपर्याप्त हो तो ₹200',
      // Tour texts
      yourWithdrawalDetails: 'आपकी निकासी विवरण',
      hereYouCanSee: 'यहाँ आप देख सकते हैं',
      processingFees: 'प्रसंस्करण शुल्क और चार्ज',
      repaymentSchedule: 'वापसी अनुसूची',
      repaymentDetails: 'वापसी विवरण',
      repaymentDetailsText: 'यह अनुभाग दिखाता है कि कब और कैसे राशि वापस की जाएगी',
      withdrawalTerms: 'निकासी शर्तें',
      importantTerms: 'महत्वपूर्ण शर्तें',
      withdrawalTermsText: 'कृपया इन महत्वपूर्ण नियमों और शर्तों की समीक्षा करें',
      // EWA Application Pages
      ewaApplication: 'EWA आवेदन',
      setupEarnedWageAccess: 'अपना अर्जित वेतन पहुंच खाता स्थापित करें',
      ewaConsentSetup: 'EWA सहमति और सेटअप',
      completeSetupEarnedWageAccess: 'अपने अर्जित वेतन पहुंच खाते के लिए सेटअप पूरा करें',
      consentAuthorization: 'सहमति और प्राधिकरण',
      consentText: 'मैं एतद्द्वारा सहमति देता हूँ और कंपनी को अर्जित वेतन पहुंच स्थापित करने के उद्देश्य से मेरे नियोक्ता से मेरी रोजगार और वेतन जानकारी प्राप्त करने के लिए अधिकृत करता हूँ। मैं समझता हूँ कि यह जानकारी केवल EWA मूल्यांकन और अनुमोदन के लिए उपयोग की जाएगी।',
      agreeTermsConditions: 'मैं नियमों और शर्तों से सहमत हूँ',
      yourEWALimits: 'आपकी EWA सीमा',
      maxDrawdown: 'अधिकतम निकासी',
      basedOnSalary: 'आपके वेतन के आधार पर आप वेतन दिवस से पहले उपरोक्त राशि तक निकाल सकते हैं',
      completeSetupProceedMandate: 'सेटअप पूरा करें और जनादेश पर आगे बढ़ें',
      kycInfoAutomaticallyFilled: 'आपकी KYC जानकारी स्वचालित रूप से भर दी गई है। आप EWA का उपयोग शुरू कर सकते हैं',
      // EWA Success Page
      ewaAgreementSignedSuccessfully: 'EWA समझौता सफलतापूर्वक हस्ताक्षरित!',
      ewaAgreementProcessed: 'आपका EWA समझौता डिजिटल रूप से हस्ताक्षरित और प्रसंस्करित किया गया है। आपको जल्द ही अपने डैशबोर्ड पर पुनर्निर्देशित किया जाएगा।',
      agreementSignedActivated: 'समझौता हस्ताक्षरित और सक्रिय। अब आप अपनी EWA सेवाओं का उपयोग कर सकते हैं।',
      settingUpEWA: 'EWA सेटअप हो रहा है...',
      // EWA Digital Signature
      keyTermsEWAAgreement: 'आपके EWA समझौते की मुख्य शर्तें',
      maxWithdrawalMonthly: 'अधिकतम निकासी',
      withdrawalFrequency: 'निकासी आवृत्ति',
      monthly: 'मासिक',
      noInterestFees: 'कोई ब्याज या शुल्क नहीं लिया जाता',
      autoSalaryDeduction: 'वेतन दिवस पर स्वचालित वेतन कटौती',
      bankMandateAuth: 'बैंक जनादेश प्राधिकरण',
      privacyDataTerms: 'गोपनीयता और डेटा उपयोग की शर्तें',
      digitalSignature: 'डिजिटल हस्ताक्षर',
      signContractAcknowledge: '"अनुबंध पर हस्ताक्षर करें" पर क्लिक करके, मैं स्वीकार करता हूं कि:',
      readUnderstoodAgreement: 'मैंने पूरा EWA समझौता पढ़ा और समझा है',
      agreeAllTermsDocument: 'मैं दस्तावेज में उल्लिखित सभी नियमों और शर्तों से सहमत हूं',
      authorizeAutoDeduction: 'मैं समझौते के अनुसार स्वचालित कटौती सेटअप को अधिकृत करता हूं',
      digitalSignatureLegallyBinding: 'यह डिजिटल हस्ताक्षर कानूनी रूप से बाध्यकारी है',
      signContract: 'अनुबंध पर हस्ताक्षर करें'
    }
  },

  // Loan pages
  loan: {
    en: {
      newLoanTitle: 'Loan Application', 
      newLoanSubtitle: 'Complete your loan application with pre-filled KYC information',
      title: 'Your Loan Applications',
      subtitle: 'Track all your loan applications and their current status',
      loanAmount: 'Loan Amount',
      tenure: 'Tenure',
      submitNewApplication: 'Submit New Application',
      applicationInProgress: 'Application in Progress',
      consent: 'Consent & Authorization',
      consentText: 'I hereby consent and authorize the company to fetch my employment and salary information from my employer for the purpose of processing this loan application.',
      fetchingInfo: 'Fetching Information',
      fetchingInfoText: 'We are currently retrieving your employment and salary details from your employer.',
      applicationSubmitted: 'Application Submitted Successfully!',
      applicationSubmittedText: 'Your loan application has been submitted successfully. You can track your application status using the application ID below.',
      // Status translations
      kycDone: 'KYC Done',
      pending: 'Pending',
      approved: 'Approved',
      documentCheck: 'Document Check',
      mandateCompleted: 'Mandate Completed',
      completed: 'Completed',
      disbursed: 'Disbursed',
      closed: 'Closed',
      rejected: 'Rejected',
      // Months
      months: [
        '1 Month', '2 Months', '3 Months', '4 Months', '5 Months', '6 Months',
        '7 Months', '8 Months', '9 Months', '10 Months', '11 Months', '12 Months'
      ],
      // Disbursement Details Page
      loanDisbursementDetails: 'Loan Disbursement Details',
      loanCompletionDetails: 'Loan Completion Details',
      trackPaymentsMessage: 'Track your loan payments and EMI schedule',
      loanCompletionMessage: 'Your loan has been successfully completed. All EMIs have been paid.',
      backToApplications: 'Back to Applications',
      loanSummary: 'Loan Summary',
      disbursedAmount: 'Disbursed Amount',
      monthlyEMI: 'Monthly EMI',
      totalEMIs: 'Total EMIs',
      payments: 'payments',
      paymentStatusOverview: 'Payment Status Overview',
      paidEMIs: 'Paid EMIs',
      overdueEMIs: 'Overdue EMIs',
      upcomingEMIs: 'Upcoming EMIs',
      successfullyPaid: 'Successfully paid',
      pastDueDate: 'Past due date',
      futurePayments: 'Future payments',
      // EMI Schedule
      emiPaymentSchedule: 'EMI Payment Schedule',
      emiNumber: 'EMI #',
      dueDate: 'Due Date',
      amount: 'Amount',
      paidDate: 'Paid Date',
      paid: 'Paid',
      overdue: 'Overdue',
      upcoming: 'Upcoming',
      // Loan Terms
      loanTermsConditions: 'Loan Terms & Conditions',
      paymentTerms: 'Payment Terms',
      interestCharges: 'Interest & Charges',
      emiAutoDeduction: 'EMI payments are automatically deducted on the 15th of each month',
      latePaymentCharges: 'Late payment charges: ₹500 if not paid within 5 days of due date',
      prepaymentCharges: 'Prepayment charges: 2% if loan is closed before 6 months',
      interestRateText: 'Interest rate: {rate}% p.a. (fixed for entire tenure)',
      totalInterestPayable: 'Total interest payable',
      totalAmountPayable: 'Total amount payable',
      // Loan Mandate and Agreement Pages
      mandateAndAgreement: 'Mandate and agreement',
      completeStepsLoanApplication: 'Complete the following steps to proceed with your loan application',
      enachMandate: 'Enach Mandate',
      eSignature: 'E-Signature',
      reviewLoanTerms: 'Review Loan Terms',
      digitallySignAgreement: 'Digitally sign your loan agreement and related documents',
      completeMandateFirst: 'Complete mandate first',
      documentCheckProgress: 'Document Check Progress',
      ofCompleted: '{count} of {total} completed',
      completeBothSteps: 'Complete both steps to proceed with your loan application',
      // Loan Terms Page
      reviewLoanDetailsBeforeProceeding: 'Please review your loan details before proceeding',
      backToDocumentCheck: 'Back to Document Check',
      firstEMIDate: 'First EMI Date',
      paymentsText: '{count} payments',
      // E-Signature Page
      eSignatureContractReview: 'E-Signature & Contract Review',
      reviewAndSignLoanAgreement: 'Please review and sign your loan agreement contract',
      loanAgreementContract: 'Loan Agreement Contract',
      reviewTermsBeforeSigning: 'Please carefully review the terms and conditions of your loan agreement before signing.',
      contractDocument: 'Contract Document',
      openInNewTab: 'Open in New Tab',
      // Form Labels
      loanDetails: 'Loan Details',
      loanDetailsHelp: 'Enter your desired loan amount and select the repayment period.',
      loanAmountPlaceholder: 'Enter loan amount (e.g., 50000)',
      selectTenure: 'Select tenure',
      // Loan Application Tour Texts
      welcomeToLoanApplication: 'Welcome to Loan Application! 💰',
      aboutToStartLoanProcess: 'You\'re about to start your loan application process.',
      kycVerifiedFasterProcess: 'Since your KYC is verified, the process will be much faster!',
      chooseYourLanguage: 'Choose Your Language 🌐',
      selectPreferredLanguage: 'Select your preferred language:',
      englishDefaultLanguage: 'English - Default language',
      hindiLanguage: 'Hindi - हिंदी',
      chooseComfortable: 'Choose what you\'re most comfortable with!',
      loanApplicationForm: 'Loan Application Form 📝',
      formWillAsk: 'The form below will:',
      askLoanAmountTenure: 'Ask for loan amount and tenure',
      showConsentAuthorization: 'Show consent and authorization',
      simulateInfoFetching: 'Simulate information fetching',
      submitYourApplication: 'Submit your application',
      fillDetailsSubmit: 'Fill in the details and submit your application!',
      // Loan Form Tour Texts (LoanForm.tsx)
      readAcceptConsentTerms: 'Read and accept the consent terms to proceed with your application.',
      fetchingEmploymentInfo: 'We are fetching your employment information from your employer.',
      fillLoanDetailsTour: 'Fill in your loan amount and preferred tenure period.',
      useActionButtonsTour: 'Use these buttons to submit a new application (when allowed) or return to the services menu.',
      // Mandate Screen Tour Texts
      welcomeMandateSetup: 'Welcome to Mandate Setup! 📋',
      mandatePermissionExplain: 'This is where you give permission for automatic payments from your bank account.',
      mandateImportantPayback: 'This is important - it\'s how you\'ll pay back your loan!',
      yourMandateDetails: 'Your Mandate Details 💳',
      mandateDetailsHere: 'Here you can see:',
      loanAmountEMIDetails: 'Your loan amount and EMI details',
      bankAccountInformation: 'Your bank account information',
      paymentDeductionTiming: 'When payments will be deducted',
      checkDetailsCorrect: 'Check that all your details are correct!',
      authenticationMethod: 'Authentication Method 🔐',
      chooseVerifyMethod: 'Choose how you want to verify:',
      netBankingOption: 'Net Banking - Use your bank login',
      debitCardOption: 'Debit Card - Use your ATM card',
      aadhaarOption: 'Aadhaar - Use your Aadhaar number',
      netBankingEasiest: 'Net Banking is usually the easiest option!',
      importantAuthorization: 'Important Authorization ✅',
      beforeProceedMust: 'Before you can proceed:',
      mustCheckBoxBelow: 'You must check the box below',
      agreeAutomaticPayments: 'This means you agree to automatic payments',
      understandTermsConditions: 'You understand the terms and conditions',
      authorizeEMIDeduction: 'You authorize the bank to deduct EMIs',
      checkWhenReady: 'Only check this when you\'re ready to proceed!',
      // ESignature Page Texts
      welcomeESignature: 'Welcome to E-Signature! ✍️',
      finalStepLoanApp: 'This is the final step of your loan application.',
      reviewSignContract: 'You\'ll review and sign your loan agreement contract!',
      reviewYourContract: 'Step 1: Review Your Contract 📄',
      beforeSigning: 'Before signing:',
      readContractCarefully: 'Read through the entire contract carefully',
      checkLoanTermsConditions: 'Check all loan terms and conditions',
      verifyPersonalDetails: 'Verify your personal details',
      understandPaymentObligations: 'Understand your payment obligations',
      takeTimeReview: 'Take your time - this is a legal document!',
      digitalSigningProcess: 'Step 2: Digital Signing Process 🔐',
      whenClickSignContract: 'When you click "Sign Contract":',
      digitalSignatureCreated: 'Your digital signature will be created',
      contractLegallyBinding: 'The contract will be legally binding',
      seeConfirmationMessage: 'You\'ll see a confirmation message',
      redirectedMainPage: 'You\'ll be redirected back to the main page',
      clickWhenReady: 'Only click when you\'re ready to commit!',
      signingYourContract: 'Signing Your Contract',
      waitProcessSignature: 'Please wait while we process your digital signature...',
      processMayTakeMoments: 'This process may take a few moments. Please do not close this page.',
      // Important Terms for Loan Terms Screen
      importantTermsConditions: 'Important Terms & Conditions',
      emiAutoDeductionBank: 'EMI payments will be automatically deducted from your registered bank account on the 15th of each month',
      latePaymentChargesBankText: 'Late payment charges of ₹500 will be applicable if EMI is not paid within 5 days of due date',
      prepaymentChargesBankText: 'Prepayment charges of 2% will be applicable if loan is closed before 6 months',
      interestRateFixed: 'Interest rate is fixed for the entire loan tenure and will not change',
      loanDisbursementProcessing: 'Loan disbursement will be processed within 2-3 working days after document completion',
      // Acceptance Section
      acceptance: 'Acceptance',
      acceptanceText: 'By clicking "Accept & Proceed", you acknowledge that you have read and understood all the loan terms and conditions, including the EMI amount, interest rate, and payment schedule. You agree to repay the loan as per the agreed terms.',
      acceptProceedMandate: 'Accept & Proceed to Mandate',
      acceptanceRecorded: 'Your acceptance will be recorded and you will be redirected to the mandate setup',
      // EWA New Application Tour Texts
      welcomeToEWASetup: 'Welcome to EWA Setup! 💳',
      ewaExplanation: 'EWA (Earned Wage Access) lets you access your earned wages before payday.',
      noInterestNoFees: 'No interest, no fees - just instant access to your money!',
      ewaConfigurationSettings: 'EWA Configuration Settings ⚙️',
      setupYourPreferences: 'Set up your preferences:',
      maxWithdrawalAmountSetting: 'Maximum withdrawal amount - How much you can take out',
      withdrawalFrequencySetting: 'Withdrawal frequency - How often you can withdraw',
      settingsHelpControl: 'These settings help control your spending',
      configureAccordingNeeds: 'Configure according to your needs!',
      // EWA Dashboard Tour Texts
      welcomeToEWADashboard: 'Welcome to Your EWA Dashboard! 💳',
      ewaControlCenter: 'This is your Earned Wage Access control center.',
      trackWithdrawalsManage: 'Track your withdrawals and manage your EWA account!',
      yourEWABalanceOverview: 'Your EWA Balance Overview 💰',
      hereYouCanSee: 'Here you can see:',
      yourMaxWithdrawalLimit: 'Your maximum withdrawal limit',
      availableBalanceWithdrawal: 'Available balance for withdrawal',
      totalAmountWithdrawnMonth: 'Total amount withdrawn this month',
      keepTrackSpendingLimits: 'Keep track of your spending limits!',
      withdrawalRequests: 'Withdrawal Requests 📋',
      thisSectionShows: 'This section shows:',
      allYourWithdrawalRequests: 'All your withdrawal requests',
      currentStatusEachRequest: 'Current status of each request',
      requestHistoryDetails: 'Request history and details',
      monitorWithdrawalActivity: 'Monitor your withdrawal activity!',
      requestNewWithdrawal: 'Request New Withdrawal ➕',
      whenYouNeedMoney: 'When you need money:',
      clickNewWithdrawalRequest: 'Click "New Withdrawal Request"',
      enterAmountYouNeed: 'Enter the amount you need',
      submitYourRequest: 'Submit your request',
      moneyTransferredBank: 'Money will be transferred to your bank',
      accessEarnedWagesAnytime: 'Access your earned wages anytime!',
      // Loan Disbursement Details Tour Texts
      welcomeToLoanDashboard: 'Welcome to Your Loan Dashboard! 🎉',
      loanDashboardExplanation: 'This page shows you everything about your loan after the money has been sent to your bank account.',
      trackPaymentsAndNext: 'You can track your payments and see what\'s coming next!',
      yourLoanSummaryDashboard: 'Your Loan Summary 💰',
      loanSummaryHereYouCanSee: 'Here you can see:',
      howMuchMoneyReceived: 'How much money you received',
      monthlyPaymentAmount: 'Your monthly payment amount',
      totalNumberPayments: 'Total number of payments to make',
      loanOverviewKeepHandy: 'This is your loan overview - keep these numbers handy!',
      paymentStatusOverviewDashboard: 'Payment Status Overview 📊',
      paymentStatusShows: 'This shows you:',
      howManyPaymentsMade: 'How many payments you\'ve already made',
      anyLatePayments: 'If you have any late payments',
      howManyPaymentsComing: 'How many payments are coming up',
      keepTrackPaymentProgress: 'Keep track of your payment progress!',
      completeEMISchedule: 'Complete EMI Schedule 📅',
      emiScheduleTableShows: 'This table shows you:',
      everyPaymentDate: 'Every payment date for your loan',
      howMuchPayEachMonth: 'How much to pay each month',
      whichPaymentsDone: 'Which payments are done and which are coming',
      ifPaymentsLate: 'If any payments are late',
      paymentRoadmapCheck: 'This is your payment roadmap - check it regularly!',
      importantLoanRules: 'Important Loan Rules ⚠️',
      rememberImportantPoints: 'Remember these important points:',
      paymentsdue15th: 'Payments are due on the 15th of each month',
      latePaymentsCost500: 'Late payments cost ₹500 extra',
      payEarlySmallCharge: 'You can pay early but there\'s a small charge',
      interestRateStaysSame: 'Interest rate stays the same throughout',
      followingRulesSavesMoney: 'Following these rules saves you money!'
    },
    hi: {
      newLoanTitle: 'लोन आवेदन',
      newLoanSubtitle: 'पहले से भरी गई केवाईसी जानकारी के साथ अपना लोन आवेदन पूरा करें',
      title: 'आपके ऋण आवेदन',
      subtitle: 'अपने सभी ऋण आवेदनों और उनकी वर्तमान स्थिति को ट्रैक करें',
      loanAmount: 'ऋण राशि',
      tenure: 'अवधि',
      submitNewApplication: 'नया आवेदन जमा करें',
      applicationInProgress: 'आवेदन प्रगति में',
      consent: 'सहमति और प्राधिकरण',
      consentText: 'मैं यहां सहमति देता/देती हूं और कंपनी को इस ऋण आवेदन के प्रसंस्करण के उद्देश्य से मेरे नियोक्ता से मेरी रोजगार और वेतन जानकारी प्राप्त करने का अधिकार देता/देती हूं।',
      fetchingInfo: 'जानकारी प्राप्त कर रहे हैं',
      fetchingInfoText: 'हम वर्तमान में आपके नियोक्ता से आपकी रोजगार और वेतन विवरण प्राप्त कर रहे हैं।',
      applicationSubmitted: 'आवेदन सफलतापूर्वक जमा किया गया!',
      applicationSubmittedText: 'आपका ऋण आवेदन सफलतापूर्वक जमा किया गया है। आप नीचे दिए गए आवेदन आईडी का उपयोग करके अपने आवेदन की स्थिति ट्रैक कर सकते हैं।',
      // Status translations
      kycDone: 'KYC पूर्ण',
      pending: 'लंबित',
      approved: 'स्वीकृत',
      documentCheck: 'दस्तावेज़ जांच',
      mandateCompleted: 'जनादेश पूर्ण',
      completed: 'पूर्ण',
      disbursed: 'वितरित',
      closed: 'बंद',
      rejected: 'अस्वीकृत',
      // Months
      months: [
        '1 महीना', '2 महीने', '3 महीने', '4 महीने', '5 महीने', '6 महीने',
        '7 महीने', '8 महीने', '9 महीने', '10 महीने', '11 महीने', '12 महीने'
      ],
      // Disbursement Details Page
      loanDisbursementDetails: 'लोन वितरण विवरण',
      loanCompletionDetails: 'लोन पूर्णता विवरण',
      trackPaymentsMessage: 'अपने लोन भुगतान और EMI शेड्यूल को ट्रैक करें',
      loanCompletionMessage: 'आपका लोन सफलतापूर्वक पूरा हो गया है। सभी EMI का भुगतान हो गया है।',
      backToApplications: 'आवेदनों पर वापस जाएं',
      loanSummary: 'लोन सारांश',
      disbursedAmount: 'वितरित राशि',
      monthlyEMI: 'मासिक EMI',
      totalEMIs: 'कुल EMI',
      payments: 'भुगतान',
      paymentStatusOverview: 'भुगतान स्थिति अवलोकन',
      paidEMIs: 'भुगतान की गई EMI',
      overdueEMIs: 'बकाया EMI',
      upcomingEMIs: 'आगामी EMI',
      successfullyPaid: 'सफलतापूर्वक भुगतान',
      pastDueDate: 'देय तिथि बीत गई',
      futurePayments: 'भविष्य के भुगतान',
      // EMI Schedule
      emiPaymentSchedule: 'EMI भुगतान अनुसूची',
      emiNumber: 'EMI #',
      dueDate: 'देय तिथि',
      amount: 'राशि',
      paidDate: 'भुगतान तिथि',
      paid: 'भुगतान',
      overdue: 'बकाया',
      upcoming: 'आगामी',
      // Loan Terms
      loanTermsConditions: 'लोन नियम और शर्तें',
      paymentTerms: 'भुगतान की शर्तें',
      interestCharges: 'ब्याज और शुल्क',
      emiAutoDeduction: 'EMI भुगतान हर महीने की 15 तारीख को स्वचालित रूप से काट लिया जाता है',
      latePaymentCharges: 'देर से भुगतान शुल्क: यदि देय तिथि के 5 दिन के भीतर भुगतान नहीं किया तो ₹500',
      prepaymentCharges: 'पूर्व भुगतान शुल्क: यदि लोन 6 महीने से पहले बंद किया जाए तो 2%',
      interestRateText: 'ब्याज दर: {rate}% सालाना (पूरी अवधि के लिए निश्चित)',
      totalInterestPayable: 'कुल देय ब्याज',
      totalAmountPayable: 'कुल देय राशि',
      // Loan Mandate and Agreement Pages
      mandateAndAgreement: 'जनादेश और समझौता',
      completeStepsLoanApplication: 'अपने लोन आवेदन के साथ आगे बढ़ने के लिए निम्नलिखित चरणों को पूरा करें',
      enachMandate: 'ईनैक जनादेश',
      eSignature: 'ई-हस्ताक्षर',
      reviewLoanTerms: 'लोन नियम समीक्षा करें',
      digitallySignAgreement: 'अपने लोन समझौते और संबंधित दस्तावेजों पर डिजिटल रूप से हस्ताक्षर करें',
      completeMandateFirst: 'पहले जनादेश पूरा करें',
      documentCheckProgress: 'दस्तावेज जांच प्रगति',
      ofCompleted: '{total} में से {count} पूर्ण',
      completeBothSteps: 'अपने लोन आवेदन के साथ आगे बढ़ने के लिए दोनों चरणों को पूरा करें',
      // Loan Terms Page
      reviewLoanDetailsBeforeProceeding: 'आगे बढ़ने से पहले कृपया अपने लोन विवरण की समीक्षा करें',
      backToDocumentCheck: 'दस्तावेज जांच पर वापस जाएं',
      firstEMIDate: 'पहली EMI तिथि',
      paymentsText: '{count} भुगतान',
      // E-Signature Page
      eSignatureContractReview: 'ई-हस्ताक्षर और अनुबंध समीक्षा',
      reviewAndSignLoanAgreement: 'कृपया अपने लोन समझौते की समीक्षा करें और हस्ताक्षर करें',
      loanAgreementContract: 'लोन समझौता अनुबंध',
      reviewTermsBeforeSigning: 'कृपया हस्ताक्षर करने से पहले अपने लोन समझौते के नियमों और शर्तों की सावधानीपूर्वक समीक्षा करें।',
      contractDocument: 'अनुबंध दस्तावेज',
      openInNewTab: 'नए टैब में खोलें',
      // Form Labels
      loanDetails: 'लोन विवरण',
      loanDetailsHelp: 'अपनी वांछित लोन राशि दर्ज करें और चुकौती अवधि का चयन करें।',
      loanAmountPlaceholder: 'लोन राशि दर्ज करें (जैसे, 50000)',
      selectTenure: 'अवधि चुनें',
      // Loan Application Tour Texts
      welcomeToLoanApplication: 'लोन आवेदन में आपका स्वागत है! 💰',
      aboutToStartLoanProcess: 'आप अपनी लोन आवेदन प्रक्रिया शुरू करने वाले हैं।',
      kycVerifiedFasterProcess: 'चूंकि आपका KYC सत्यापित है, प्रक्रिया बहुत तेज़ होगी!',
      chooseYourLanguage: 'अपनी भाषा चुनें 🌐',
      selectPreferredLanguage: 'अपनी पसंदीदा भाषा चुनें:',
      englishDefaultLanguage: 'English - डिफ़ॉल्ट भाषा',
      hindiLanguage: 'Hindi - हिंदी',
      chooseComfortable: 'जो आपके लिए सबसे सुविधाजनक है वह चुनें!',
      loanApplicationForm: 'लोन आवेदन फॉर्म 📝',
      formWillAsk: 'नीचे दिया गया फॉर्म:',
      askLoanAmountTenure: 'लोन राशि और अवधि के लिए पूछेगा',
      showConsentAuthorization: 'सहमति और प्राधिकरण दिखाएगा',
      simulateInfoFetching: 'जानकारी प्राप्त करने का अनुकरण करेगा',
      submitYourApplication: 'आपका आवेदन जमा करेगा',
      fillDetailsSubmit: 'विवरण भरें और अपना आवेदन जमा करें!',
      // Loan Form Tour Texts (LoanForm.tsx)
      readAcceptConsentTerms: 'अपने आवेदन के साथ आगे बढ़ने के लिए सहमति की शर्तों को पढ़ें और स्वीकार करें।',
      fetchingEmploymentInfo: 'हम आपके नियोक्ता से आपकी रोजगार की जानकारी प्राप्त कर रहे हैं।',
      fillLoanDetailsTour: 'अपनी लोन राशि और पसंदीदा अवधि भरें।',
      useActionButtonsTour: 'नया आवेदन जमा करने (जब अनुमति हो) या सेवा मेनू पर वापस जाने के लिए इन बटन का उपयोग करें।',
      // Mandate Screen Tour Texts
      welcomeMandateSetup: 'मैंडेट सेटअप में आपका स्वागत है! 📋',
      mandatePermissionExplain: 'यहाँ आप अपने बैंक खाते से स्वचालित भुगतान की अनुमति देते हैं।',
      mandateImportantPayback: 'यह महत्वपूर्ण है - इसी तरह आप अपना लोन वापस करेंगे!',
      yourMandateDetails: 'आपके मैंडेट विवरण 💳',
      mandateDetailsHere: 'यहाँ आप देख सकते हैं:',
      loanAmountEMIDetails: 'आपकी लोन राशि और EMI विवरण',
      bankAccountInformation: 'आपके बैंक खाते की जानकारी',
      paymentDeductionTiming: 'भुगतान कब काटे जाएंगे',
      checkDetailsCorrect: 'जांच लें कि आपके सभी विवरण सही हैं!',
      authenticationMethod: 'प्रमाणीकरण विधि 🔐',
      chooseVerifyMethod: 'आप कैसे सत्यापित करना चाहते हैं चुनें:',
      netBankingOption: 'नेट बैंकिंग - अपने बैंक लॉगिन का उपयोग करें',
      debitCardOption: 'डेबिट कार्ड - अपने ATM कार्ड का उपयोग करें',
      aadhaarOption: 'आधार - अपने आधार नंबर का उपयोग करें',
      netBankingEasiest: 'नेट बैंकिंग आमतौर पर सबसे आसान विकल्प है!',
      importantAuthorization: 'महत्वपूर्ण प्राधिकरण ✅',
      beforeProceedMust: 'आगे बढ़ने से पहले आपको चाहिए:',
      mustCheckBoxBelow: 'आपको नीचे दिए गए बॉक्स को चेक करना होगा',
      agreeAutomaticPayments: 'इसका मतलब है कि आप स्वचालित भुगतान से सहमत हैं',
      understandTermsConditions: 'आप नियम और शर्तों को समझते हैं',
      authorizeEMIDeduction: 'आप बैंक को EMI काटने का अधिकार देते हैं',
      checkWhenReady: 'केवल तभी चेक करें जब आप आगे बढ़ने के लिए तैयार हों!',
      // ESignature Page Texts
      welcomeESignature: 'ई-हस्ताक्षर में आपका स्वागत है! ✍️',
      finalStepLoanApp: 'यह आपके लोन आवेदन का अंतिम चरण है।',
      reviewSignContract: 'आप अपने लोन समझौते की समीक्षा करेंगे और हस्ताक्षर करेंगे!',
      reviewYourContract: 'चरण 1: अपने अनुबंध की समीक्षा करें 📄',
      beforeSigning: 'हस्ताक्षर करने से पहले:',
      readContractCarefully: 'पूरे अनुबंध को ध्यान से पढ़ें',
      checkLoanTermsConditions: 'सभी लोन नियम और शर्तों की जांच करें',
      verifyPersonalDetails: 'अपने व्यक्तिगत विवरण सत्यापित करें',
      understandPaymentObligations: 'अपने भुगतान दायित्वों को समझें',
      takeTimeReview: 'अपना समय लें - यह एक कानूनी दस्तावेज है!',
      digitalSigningProcess: 'चरण 2: डिजिटल हस्ताक्षर प्रक्रिया 🔐',
      whenClickSignContract: 'जब आप "अनुबंध पर हस्ताक्षर करें" पर क्लिक करते हैं:',
      digitalSignatureCreated: 'आपका डिजिटल हस्ताक्षर बनाया जाएगा',
      contractLegallyBinding: 'अनुबंध कानूनी रूप से बाध्यकारी होगा',
      seeConfirmationMessage: 'आपको एक पुष्टिकरण संदेश दिखाई देगा',
      redirectedMainPage: 'आपको मुख्य पृष्ठ पर वापस भेज दिया जाएगा',
      clickWhenReady: 'केवल तभी क्लिक करें जब आप प्रतिबद्ध होने के लिए तैयार हों!',
      signingYourContract: 'आपके अनुबंध पर हस्ताक्षर हो रहे हैं',
      waitProcessSignature: 'कृपया प्रतीक्षा करें जबकि हम आपके डिजिटल हस्ताक्षर को प्रोसेस करते हैं...',
      processMayTakeMoments: 'इस प्रक्रिया में कुछ समय लग सकता है। कृपया इस पेज को बंद न करें।',
      // Important Terms for Loan Terms Screen
      importantTermsConditions: 'महत्वपूर्ण नियम और शर्तें',
      emiAutoDeductionBank: 'EMI भुगतान आपके पंजीकृत बैंक खाते से हर महीने की 15 तारीख को स्वचालित रूप से काट लिया जाएगा',
      latePaymentChargesBankText: 'यदि EMI देय तिथि के 5 दिन के भीतर भुगतान नहीं किया तो ₹500 का देर से भुगतान शुल्क लागू होगा',
      prepaymentChargesBankText: 'यदि लोन 6 महीने से पहले बंद किया जाए तो 2% का पूर्व भुगतान शुल्क लागू होगा',
      interestRateFixed: 'ब्याज दर पूरी लोन अवधि के लिए निश्चित है और बदली नहीं जाएगी',
      loanDisbursementProcessing: 'दस्तावेज पूरा होने के बाद लोन वितरण 2-3 कार्य दिवसों में प्रसंस्करित किया जाएगा',
      // Acceptance Section
      acceptance: 'स्वीकृति',
      acceptanceText: '"स्वीकार और आगे बढ़ें" पर क्लिक करके, आप स्वीकार करते हैं कि आपने सभी लोन नियम और शर्तों को पढ़ा और समझा है, जिसमें EMI राशि, ब्याज दर, और भुगतान अनुसूची शामिल है। आप सहमत शर्तों के अनुसार लोन चुकाने के लिए सहमत हैं।',
      acceptProceedMandate: 'स्वीकार करें और जनादेश पर आगे बढ़ें',
      acceptanceRecorded: 'आपकी स्वीकृति दर्ज की जाएगी और आपको जनादेश सेटअप पर पुनर्निर्देशित किया जाएगा',
      // EWA New Application Tour Texts
      welcomeToEWASetup: 'EWA सेटअप में आपका स्वागत है! 💳',
      ewaExplanation: 'EWA (अर्जित मजदूरी पहुंच) आपको पेडे से पहले अपनी अर्जित मजदूरी तक पहुंचने की सुविधा देता है।',
      noInterestNoFees: 'कोई ब्याज नहीं, कोई फीस नहीं - बस अपने पैसे तक तुरंत पहुंच!',
      ewaConfigurationSettings: 'EWA कॉन्फ़िगरेशन सेटिंग्स ⚙️',
      setupYourPreferences: 'अपनी प्राथमिकताएं सेट करें:',
      maxWithdrawalAmountSetting: 'अधिकतम निकासी राशि - आप कितना निकाल सकते हैं',
      withdrawalFrequencySetting: 'निकासी आवृत्ति - आप कितनी बार निकाल सकते हैं',
      settingsHelpControl: 'ये सेटिंग्स आपके खर्च को नियंत्रित करने में मदद करती हैं',
      configureAccordingNeeds: 'अपनी आवश्यकताओं के अनुसार कॉन्फ़िगर करें!',
      // EWA Dashboard Tour Texts
      welcomeToEWADashboard: 'आपके EWA डैशबोर्ड में आपका स्वागत है! 💳',
      ewaControlCenter: 'यह आपका अर्जित मजदूरी पहुंच नियंत्रण केंद्र है।',
      trackWithdrawalsManage: 'अपनी निकासी को ट्रैक करें और अपने EWA खाते का प्रबंधन करें!',
      yourEWABalanceOverview: 'आपका EWA बैलेंस अवलोकन 💰',
      hereYouCanSee: 'यहाँ आप देख सकते हैं:',
      yourMaxWithdrawalLimit: 'आपकी अधिकतम निकासी सीमा',
      availableBalanceWithdrawal: 'निकासी के लिए उपलब्ध बैलेंस',
      totalAmountWithdrawnMonth: 'इस महीने निकाली गई कुल राशि',
      keepTrackSpendingLimits: 'अपनी खर्च सीमा का ट्रैक रखें!',
      withdrawalRequests: 'निकासी अनुरोध 📋',
      thisSectionShows: 'यह अनुभाग दिखाता है:',
      allYourWithdrawalRequests: 'आपके सभी निकासी अनुरोध',
      currentStatusEachRequest: 'प्रत्येक अनुरोध की वर्तमान स्थिति',
      requestHistoryDetails: 'अनुरोध इतिहास और विवरण',
      monitorWithdrawalActivity: 'अपनी निकासी गतिविधि की निगरानी करें!',
      requestNewWithdrawal: 'नई निकासी का अनुरोध करें ➕',
      whenYouNeedMoney: 'जब आपको पैसे की जरूरत हो:',
      clickNewWithdrawalRequest: '"नई निकासी अनुरोध" पर क्लिक करें',
      enterAmountYouNeed: 'आपको जितनी राशि चाहिए उसे दर्ज करें',
      submitYourRequest: 'अपना अनुरोध जमा करें',
      moneyTransferredBank: 'पैसा आपके बैंक में ट्रांसफर हो जाएगा',
      accessEarnedWagesAnytime: 'अपनी अर्जित मजदूरी तक कभी भी पहुंचें!',
      // Loan Disbursement Details Tour Texts
      welcomeToLoanDashboard: 'आपके लोन डैशबोर्ड में आपका स्वागत है! 🎉',
      loanDashboardExplanation: 'यह पेज आपको आपके लोन के बारे में सब कुछ दिखाता है जब पैसा आपके बैंक खाते में भेज दिया गया हो।',
      trackPaymentsAndNext: 'आप अपने भुगतान को ट्रैक कर सकते हैं और देख सकते हैं कि आगे क्या आ रहा है!',
      yourLoanSummaryDashboard: 'आपका लोन सारांश 💰',
      loanSummaryHereYouCanSee: 'यहाँ आप देख सकते हैं:',
      howMuchMoneyReceived: 'आपको कितना पैसा मिला',
      monthlyPaymentAmount: 'आपकी मासिक भुगतान राशि',
      totalNumberPayments: 'करने वाले भुगतानों की कुल संख्या',
      loanOverviewKeepHandy: 'यह आपका लोन अवलोकन है - इन नंबरों को संभाल कर रखें!',
      paymentStatusOverviewDashboard: 'भुगतान स्थिति अवलोकन 📊',
      paymentStatusShows: 'यह आपको दिखाता है:',
      howManyPaymentsMade: 'आपने कितने भुगतान पहले ही कर दिए हैं',
      anyLatePayments: 'क्या आपके कोई देर से भुगतान हैं',
      howManyPaymentsComing: 'कितने भुगतान आने वाले हैं',
      keepTrackPaymentProgress: 'अपनी भुगतान प्रगति का ट्रैक रखें!',
      completeEMISchedule: 'पूरा EMI शेड्यूल 📅',
      emiScheduleTableShows: 'यह तालिका आपको दिखाती है:',
      everyPaymentDate: 'आपके लोन की हर भुगतान तारीख',
      howMuchPayEachMonth: 'हर महीने कितना भुगतान करना है',
      whichPaymentsDone: 'कौन से भुगतान हो गए हैं और कौन से आने वाले हैं',
      ifPaymentsLate: 'यदि कोई भुगतान देर से है',
      paymentRoadmapCheck: 'यह आपका भुगतान रोडमैप है - इसे नियमित रूप से चेक करें!',
      importantLoanRules: 'महत्वपूर्ण लोन नियम ⚠️',
      rememberImportantPoints: 'इन महत्वपूर्ण बातों को याद रखें:',
      paymentsdue15th: 'भुगतान हर महीने की 15 तारीख को देय हैं',
      latePaymentsCost500: 'देर से भुगतान पर ₹500 अतिरिक्त लगता है',
      payEarlySmallCharge: 'आप जल्दी भुगतान कर सकते हैं लेकिन एक छोटा चार्ज है',
      interestRateStaysSame: 'ब्याज दर पूरे समय एक समान रहती है',
      followingRulesSavesMoney: 'इन नियमों का पालन करना आपके पैसे बचाता है!'
    }
  }

};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<SupportedLanguage>('en');

  // Load language preference from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage') as SupportedLanguage;
    if (savedLanguage && ['en', 'hi', 'te', 'kn', 'mr', 'hinglish'].includes(savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const setLanguage = (language: SupportedLanguage) => {
    setCurrentLanguage(language);
    localStorage.setItem('selectedLanguage', language);
  };

  const t = (key: string, section: string = 'common'): string | string[] => {
    try {
      const sectionTranslations = translations[section as keyof typeof translations];
      if (!sectionTranslations) {
        console.warn(`Translation section '${section}' not found`);
        return key;
      }

      // Always fallback to English if the current language doesn't exist in this section
      const supportedLanguages = ['en', 'hi'] as const;
      const effectiveLanguage = supportedLanguages.includes(currentLanguage as 'en' | 'hi') ? currentLanguage : 'en';
      
      const languageTranslations = sectionTranslations[effectiveLanguage as 'en' | 'hi'];
      if (!languageTranslations) {
        // Final fallback to English
        const englishTranslations = sectionTranslations['en'];
        return (englishTranslations as Record<string, string | string[]>)?.[key] || key;
      }

      return (languageTranslations as Record<string, string | string[]>)?.[key] || key;
    } catch (error) {
      console.warn(`Translation error for key '${key}' in section '${section}':`, error);
      return key;
    }
  };

  const value = {
    currentLanguage,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
